version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/chat
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=your_access_secret
      - JWT_REFRESH_SECRET=your_refresh_secret
    depends_on:
      - mongodb
      - redis
    networks:
      - chat-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - chat-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data: 